### ISSUE TITLE
Absolute JS path hardcoded in gallery.html

### ISSUE THREAD

**Issue by ge0rg** [mfg92/hugo-shortcode-gallery#18]
I'm running a hugo site in a subdirectory on a web-server instead of the server root.

The javascript paths in layouts/shortcodes/gallery.html are hardcoded, so that the site fails to load the JS and fails to display the gallery.

**Comment by mfg92** [comment]
I´m not sure how to solve that issue...
- I can't simply make the path relative like `../../shortcode-gallery/swipebox/js/jquery.swipebox.min.js` because how many `../` are needed depends on were the shortcode is used.
- So an alternative would be to make it configurable like `{{ $websiteRootFolder }}/shortcode-gallery/swipebox/js/jquery.swipebox.min.js`. But then it will not work when the website is served using hugos build-in server (during testing for example).
- Third option would be to inline all .js and .css files. This has its own drawbacks, but it could be an option.

Do you have any (further) suggestions?

**Comment by vmdude** [comment]
@mfg92 You could switch for instance:
https://github.com/mfg92/hugo-shortcode-gallery/blob/566bb77d13d879e5838ea40554975b182b6995aa/layouts/shortcodes/gallery.html#L50

to something like:
```html
		<script src="{{ "shortcode-gallery/lazy/jquery.lazy.min.js" | absURL }}"></script>
```

It basically just build URL from `baseURL` Hugo setting and the URL provided, and it work when using `hugo server` in-memory as well

**Comment by mfg92** [comment]
Thank you @vmdude for your good hint.

**Comment by joelsleeba** [comment]
> @mfg92 You could switch for instance:
> 
> https://github.com/mfg92/hugo-shortcode-gallery/blob/566bb77d13d879e5838ea40554975b182b6995aa/layouts/shortcodes/gallery.html#L50
> 
> to something like:
> 
> ```
> 		<script src="{{ "shortcode-gallery/lazy/jquery.lazy.min.js" | absURL }}"></script>
> ```
> 
> It basically just build URL from `baseURL` Hugo setting and the URL provided, and it work when using `hugo server` in-memory as well

I had the same issue and the fix @vmdude suggested resolved it for me, but the main branch of the code still has the old buggy code. Pls resolve

**Comment by mfg92** [comment]
You can create a pull request for this

**Comment by joelsleeba** [comment]
I've created the pull request for the fix. Lemme know if something's up. 
P.S: It's one of my first pull requests
