### ISSUE TITLE
portrait not rendered correctly in thumbnails

### ISSUE THREAD

**Issue by think-nice-things** [mfg92/hugo-shortcode-gallery#22]
If I use portrait images from my smartphone, the gallery images are _not_ displayed in portrait but all in landscape.
If I display the images in large by clicking on them, they're rendered correctly in portrait.
I guess that lightbox respects the exif orientation but thumbnail generation doesn't.
Any ideas?

**Comment by RoneoOrg** [comment]
Is there a public website where we can see the issue?

**Comment by think-nice-things** [comment]
well, not really, I'm working on a non public site for the moment.

I've mocked up a public demonstration at

https://gallerytest.zellner.org/posts/gallery-test/

(please note that I'll remove the site once the issue is done).

I guess the issue is due to some exif tags like
Orientation                     : Rotate 90 CW
Orientation                     : Rotate 270 CW

**Comment by mfg92** [comment]
I am working on a fix right now which is already mostly done. I only need a bit more time for testing and polishing.

**Comment by mfg92** [comment]
The fix is now in master. Please test it and report back.

**Comment by think-nice-things** [comment]
works perfectly, thanks!

**Comment by mfg92** [comment]
Now Hugo 0.121.2 has a new function to handle EXIF orientation called [AutoOrient](https://gohugo.io/functions/images/autoorient/). With the latest commit, hugo-shortcode-gallery uses this feature instead of the old custom implementation.

@think-nice-things Could you try this change and let me know if it works as expected?
