### ISSUE TITLE
does not work with Hugo LogBook theme

### ISSUE THREAD

**Issue by andyczerwonka** [mfg92/hugo-shortcode-gallery#24]
I followed the installation instructions, and the gallery is not rendering for me. The preview of an article that includes the gallery shortcode looks like it's trying to render something.

![image](https://user-images.githubusercontent.com/138898/124769008-5d165d80-def6-11eb-899f-e6e0e223b4e0.png)

When I go into the post, it's completely blank.

My directory structure looks correct, but maybe I'm missing something?

![image](https://user-images.githubusercontent.com/138898/124769418-aebee800-def6-11eb-8ca8-8ab8f912a3f8.png)

I have also included it in my themes directory:

```
theme = ["logbook", "hugo-shortcode-gallery"]
```

**Comment by mfg92** [comment]
I have tested hugo 0.85.0 on my website and the gallery worked. So the problem ist not that particular hugo version.

Do you have jQuery inlcuded on your site or are you using the 'loadJQuery' option (like `{{< gallery match="images/*" "  loadJQuery="true" >}}`)?

Are there any messages in your browsers console?

**Comment by andyczerwonka** [comment]
@mfg92 I am not using the `loadJQuery="true"` option, but it does look like the logbook theme include `jQuery`.

![image](https://user-images.githubusercontent.com/138898/124808838-aed1de80-df1c-11eb-8a97-5a95c811df65.png)

**Comment by andyczerwonka** [comment]
If you'd like to dig in a bit live, you can find me on Discord: andy.czerwonka#2893

**Comment by andyczerwonka** [comment]
Here's [a gist of the rendered page](https://gist.github.com/andyczerwonka/bbf432ca77d53fca8a229f90884e3f16).

**Comment by andyczerwonka** [comment]
@mfg92 My mistake, there is an error in the console.

```
Uncaught TypeError: gallery.justifiedGallery is not a function
    <anonymous> http://localhost:1313/post/picking-up-the-camera-gallery/:523
    jQuery 13
picking-up-the-camera-gallery:523:11
    <anonymous> http://localhost:1313/post/picking-up-the-camera-gallery/:523
    jQuery 13
```

**Comment by mfg92** [comment]
So i think I have found the root cause of the problem:
Your site/theme embeds/inlines jQuery at the end of the HTML. But the jQuery plugins (js files) of the gallery are loaded befor that.

So...
- if you use `loadJQuery="true"` jQuery is loaded at the right time and the plugins are loaded correctly too, but at the end the jQuery from the gallery is replaced by the jQuery of your theme/site. This jQuery does not have the plugins installed and thats why the gallery does not work.
- if you do not use `loadJQuery="true"` the jQuery plugins will not be initialized correctly as they need jQuery for that, but the embedded jQuery is only available later. -> gallery will not work

So how to handel that?
You need to change the theme or your site so that it either:
- does not include jquery on pages where the gallery shortcode is used (and use `loadJQuery="true"`)
- embed the jQuery in the header of the HTML (or at least before the jQuery plugins of the gallery) and do not use `loadJQuery="true"`

**Comment by andyczerwonka** [comment]
>     * embed the jQuery in the header of the HTML (or at least before the jQuery plugins of the gallery) and do not use `loadJQuery="true"`

I'm not sure about the lifecycle here, but you're saying that if I adjust the **LogBook Theme jQuery** to load earlier in the header, that would do it?

**Comment by andyczerwonka** [comment]
Brilliant!

```html
<!DOCTYPE html>
<html lang="{{ site.LanguageCode | default `en-US` }}">

<head>
	{{ partial "head.html" . }}
	{{ partialCached "style.html" . }}
	{{ partialCached "script.html" . }}
</head>

<body>
	{{ partialCached "preloader.html" . }}
	{{ partial "header.html" . }}
	<main>
		{{ block "main" . }}{{ end }}
	</main>
	{{ partialCached "footer.html" . }}
</body>

</html>
```
I moved the `{{ partialCached "script.html" . }}` to the head section (it was below the footer), and it renders perfectly. Thanks!!

**Comment by andyczerwonka** [comment]
@mfg92 How do you get the titles in the image like you do in your site?

**Comment by andyczerwonka** [comment]
Ah, I see it, `Sidecar files`

**Comment by geeklingo** [comment]
I have this exact same issue with aether theme but only on one post card. All the others render fine. I am using loadJQuery="true".
