### ISSUE TITLE
Can I put images into `hugo-site/static/images` ?

### ISSUE THREAD

**Issue by scillidan** [mfg92/hugo-shortcode-gallery#60]
I've read README carefully.
And in the chapter [Usage Example](https://github.com/mfg92/hugo-shortcode-gallery#usage-example), it said: `The folder must be next to the .md file where this gallery is used in`.    
So, I'm just taking a chance. 🤡

I want to use this script [hugo-picture-optimization](https://github.com/b-m-f/hugo-picture-optimization) to compress the picture. They're a little too big. But therefore, I can only put the picture in `/static/images`.

Thanks for read :)

**Comment by mfg92** [comment]
In your case I would use the `imageResizeOptions` instead of using [hugo-picture-optimization](https://github.com/b-m-f/hugo-picture-optimization). With a parameter of _"1400x1400 q85"_ you can specify the maximum height and width an image is allowed to have, larger images will get scaled down. It will use a jpeg quality of 85%, you can lower it if you want to achieve smaller images.

Use it like this:
```
{{< gallery match="images/*" imageResizeOptions ="1400x1400 q85" >}}
```

**Comment by nnzv** [comment]
I understand this is a closed issue, but is it possible to relocate our images to the `static` folder for improved organization?

**Comment by mfg92** [comment]
@nnzv hugo-shortcode-gallery needs to know (and have access to) the images during rendertime, as it will create thumbnails in this step. In this sense, images read by hugo-shortcode-gallery are not static. So the static folder is the wrong place to put the input images.
What is the problem with putting the images next to the markdown file where they are used? This is the Hugo way of handling resources (see https://gohugo.io/content-management/page-bundles/).
