### ISSUE TITLE
Clarification on filterOptions

### ISSUE THREAD

**Issue by raveenapp** [mfg92/hugo-shortcode-gallery#63]
Hi! I'd like to implement the filtering in my gallery. I see that I can filter by " EXIF tags, image description, start rating or color labels". What exif tag should I create/use if I want to filter similarly to your example site ("Favourites, birds, insects, etc.).

I really do love this gallery shortcode and thank you for all your hardwork!

**Comment by mfg92** [comment]
The `filterOptions` of my website are these:
```
[
   {label: 'Favorites', color_label: 'red'},
   {label: 'All', tags: '.*'},
   {label: 'Birds', tags: 'bird'},
   {label: 'Macro', tags: 'macro'},
   {label: 'Insects', tags: 'insect'},
   {label: 'Abstract', tags: 'abstract'},
   {label: 'Landscape', tags: 'landscape'},
   {label: 'Leafs', tags: 'plant\\|leaf|leafs collection'}
]
```

The meta file of an image may look like this:
```
{
   "ColorLabels":"r",
   "Rating":3,
   "Tags": ["published|matze.rocks","juvenile","animal|bird|oystercatcher|eurasian oystercatcher","published|matze.rocks|article|heligoland2022"]
}
```
A metadata sidecar file (like the one above) is only optional, as the metadata of the EXIF embedded in the image can be used for filtering too.

I'm not sure if this answers your question.

**Comment by raveenapp** [comment]
Ah!  I understand now. Thank you for your help :) I was able to set up the filters

**Comment by eclecticpassions** [comment]
> A metadata sidecar file (like the one above) is only optional, as the metadata of the EXIF embedded in the image can be used for filtering too.
> 
> I'm not sure if this answers your question.

Hi Matze @mfg92, I'm having a lot of trouble getting the filterOptions to work with anything other than `{label: '3 Stars', rating: '3'}`. 

It is not working for color labels eg: `{label: 'Yellow', 'Color_Labels': 'yellow'}` or filtering with the embedded exif data eg: `{label: 'GR3x', Model: 'RICOH GR IIIx'}`. Nothing happens when I click on these filter buttons, either it shows all the photos, or nothing.

I checked the photos with `exiftool -a -G1 -s` and it shows the color label metadata is under two namespaces: `[XMP-digiKam] ColorLabel : yellow` and `[XMP-xmp] Label : yellow`. For the camera model metadata it's in: `[IFD0]  Model  : RICOH GR IIIx`.

Secondly, I originally hope it was possible to read tags/keywords directly from the `[XMP-dc] Subject` embedded metadata field but from what I understand it can only be done with the additional sidecar file within Hugo? 

Thanks so much for creating this theme component for Hugo. If this works out it'll be a brilliant way of showing photos on the site. Thanks again.

Edit: My hugo.toml has this set for includeFields under [imaging.Exif] because ".*" was causing a lot of weird symbols being extracted from the metadata (seen when debugging with:
```
{{ with .Exif }}
<pre>{{ . | jsonify }}</pre>
{{ end }} 
```
After specifying includeFields instead of "all", the weird symbols and gibberish was gone.
```
[imaging]
  [imaging.exif]
    includeFields = "Copyright|Artist|Rights|Exif|Tags|Rating|FNumber|ISO|Lens|Model|Exposure|FocalLength|Title|Description"
    disableLatLong = true
    excludeFields = ''
    disableDate = false
```
